"use client";
import { add } from "@/lib/firebase/firestore";

export default function Test() {
  const analytics = {
    rooms: {
      categories: {
        executive: {
          weeks: {
            38: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            293: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 70000,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            292: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 68000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            291: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 66000,
              totalFoodOrders: 0,
            },
            290: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 7,
              avgPriceOfFood: 0,
              totalEarnings: 58000,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            289: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalEarnings: 63000,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            288: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 67000,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 7,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            287: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 7,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 62000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            9: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 7,
              avgPriceOfRooms: 0,
            },
          },
          name: "Executive",
        },
        deluxe: {
          weeks: {
            38: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 7,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            293: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 81000,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            292: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 79000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            291: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 77000,
              totalFoodOrders: 0,
            },
            290: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 7,
              avgPriceOfFood: 0,
              totalEarnings: 65000,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            289: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalEarnings: 74000,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            288: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 73000,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 7,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            287: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 7,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 71000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            9: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 7,
              avgPriceOfRooms: 0,
            },
          },
          name: "Deluxe",
        },
        suite: {
          weeks: {
            38: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 7,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            293: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 137000,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            292: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 135000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            291: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 133000,
              totalFoodOrders: 0,
            },
            290: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 7,
              avgPriceOfFood: 0,
              totalEarnings: 130000,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            289: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalEarnings: 129000,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            288: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 81000,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 7,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            287: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 127000,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 127000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            9: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 7,
              avgPriceOfRooms: 0,
            },
          },
          name: "Suite",
        },
        "super suite": {
          weeks: {
            38: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 7,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            293: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 66000,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            292: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 64000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            291: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 62000,
              totalFoodOrders: 0,
            },
            290: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 7,
              avgPriceOfFood: 0,
              totalEarnings: 59000,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            289: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalEarnings: 60000,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            288: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 57000,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 7,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            287: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 7,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 56000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            9: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 7,
              avgPriceOfRooms: 0,
            },
          },
          name: "Super Suite",
        },
      },
    },
    food: {
      categories: {
        "in-house restaurant": {
          weeks: {
            38: {
              totalEarnings: 0,
              avgDiningDuration: 0,
              totalBookings: 0,
              totalIssues: 0,
              avgPricPerOrder: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
            },
          },
          days: {
            293: {
              avgPrice: 0,
              totalIssues: 0,
              avgPricPerOrder: 0,
              totalBookings: 10,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgDiningDuration: 0,
              totalEarnings: 41000,
              avgPriceOfFood: 0,
            },
            292: {
              totalBookings: 10,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgDiningDuration: 0,
              totalEarnings: 39000,
              avgPricPerOrder: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            291: {
              avgDiningDuration: 0,
              totalBookings: 10,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPricPerOrder: 0,
              totalEarnings: 37000,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
            },
            290: {
              avgPrice: 0,
              totalIssues: 0,
              avgPricPerOrder: 0,
              totalBookings: 10,
              avgPriceOfFood: 0,
              totalEarnings: 35000,
              avgDiningDuration: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
            },
            289: {
              avgDiningDuration: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalBookings: 10,
              totalEarnings: 33000,
              avgPriceOfFood: 0,
              avgPricPerOrder: 0,
            },
            288: {
              avgPriceOfFood: 0,
              avgDiningDuration: 0,
              avgPricPerOrder: 0,
              totalEarnings: 32000,
              totalBookings: 10,
              totalIssues: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgPrice: 0,
            },
            287: {
              avgPricPerOrder: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 10,
              avgDiningDuration: 0,
              totalEarnings: 30000,
            },
          },
          months: {
            9: {
              totalIssues: 0,
              avgPrice: 0,
              totalEarnings: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgDiningDuration: 0,
              totalBookings: 10,
              avgPricPerOrder: 0,
            },
          },
          name: "In-house Restaurant",
        },
        restaurant: {
          weeks: {
            38: {
              totalEarnings: 0,
              avgDiningDuration: 0,
              totalBookings: 10,
              totalIssues: 0,
              avgPricPerOrder: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
            },
          },
          days: {
            293: {
              avgPrice: 0,
              totalIssues: 0,
              avgPricPerOrder: 0,
              totalBookings: 10,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgDiningDuration: 0,
              totalEarnings: 51000,
              avgPriceOfFood: 0,
            },
            292: {
              totalBookings: 10,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgDiningDuration: 0,
              totalEarnings: 49000,
              avgPricPerOrder: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            291: {
              avgDiningDuration: 0,
              totalBookings: 10,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPricPerOrder: 0,
              totalEarnings: 47000,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
            },
            290: {
              avgPrice: 0,
              totalIssues: 0,
              avgPricPerOrder: 0,
              totalBookings: 10,
              avgPriceOfFood: 0,
              totalEarnings: 43000,
              avgDiningDuration: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
            },
            289: {
              avgDiningDuration: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalBookings: 10,
              totalEarnings: 45000,
              avgPriceOfFood: 0,
              avgPricPerOrder: 0,
            },
            288: {
              avgPriceOfFood: 0,
              avgDiningDuration: 0,
              avgPricPerOrder: 0,
              totalEarnings: 41000,
              totalBookings: 10,
              totalIssues: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgPrice: 0,
            },
            287: {
              avgPricPerOrder: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 10,
              avgDiningDuration: 0,
              totalEarnings: 40000,
            },
          },
          months: {
            9: {
              totalIssues: 0,
              avgPrice: 0,
              totalEarnings: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgDiningDuration: 0,
              totalBookings: 0,
              avgPricPerOrder: 0,
            },
          },
          name: "Restaurant",
        },
      },
    },
    services: {
      categories: {
        spa: {
          weeks: {
            38: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            293: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 31000,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            292: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 29000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            291: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 27000,
              totalFoodOrders: 0,
            },
            290: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 5,
              avgPriceOfFood: 0,
              totalEarnings: 25000,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            289: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalEarnings: 23000,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            288: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 27000,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 5,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            287: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 5,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 31000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            9: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 5,
              avgPriceOfRooms: 0,
            },
          },
          name: "Spa",
        },
        gym: {
          weeks: {
            38: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 5,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            293: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 28700,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            292: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 24000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            291: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 22000,
              totalFoodOrders: 0,
            },
            290: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 5,
              avgPriceOfFood: 0,
              totalEarnings: 20000,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            289: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalEarnings: 18000,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            288: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 21000,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 5,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            287: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 5,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 15000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            9: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 5,
              avgPriceOfRooms: 0,
            },
          },
          name: "Gym",
        },
        laundry: {
          weeks: {
            38: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 5,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            293: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 21000,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            292: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 19000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            291: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 17000,
              totalFoodOrders: 0,
            },
            290: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 5,
              avgPriceOfFood: 0,
              totalEarnings: 15000,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            289: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalEarnings: 13000,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            288: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 11000,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 5,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            287: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 5,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 14000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            9: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 5,
              avgPriceOfRooms: 0,
            },
          },
          name: "Laundry",
        },
        pool: {
          weeks: {
            38: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 5,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            293: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 36000,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            292: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 34000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            291: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 32000,
              totalFoodOrders: 0,
            },
            290: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 5,
              avgPriceOfFood: 0,
              totalEarnings: 30000,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            289: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalEarnings: 29100,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            288: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 28700,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 5,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            287: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 5,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 25000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            9: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 0,
              avgPriceOfRooms: 0,
            },
          },
          name: "Pool",
        },
      },
    },
    issues: {
      categories: {
        rooms: {
          weeks: {
            38: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            293: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 2,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 32,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            292: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 25,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            291: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 62,
              totalFoodOrders: 0,
            },
            290: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 2,
              avgPriceOfFood: 0,
              totalEarnings: 46,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            289: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              totalEarnings: 22,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            288: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 15,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 2,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            287: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 2,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 23,
              avgPriceOfServices: 0,
            },
          },
          months: {
            9: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 2,
              avgPriceOfRooms: 0,
            },
          },
          name: "Rooms",
        },
        Food: {
          weeks: {
            38: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 2,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            293: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 2,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 14,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            292: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 11,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            291: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 13,
              totalFoodOrders: 0,
            },
            290: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 2,
              avgPriceOfFood: 0,
              totalEarnings: 15,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            289: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              totalEarnings: 19,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            288: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 12,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 2,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            287: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 2,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 16,
              avgPriceOfServices: 0,
            },
          },
          months: {
            9: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 2,
              avgPriceOfRooms: 0,
            },
          },
          name: "Food",
        },
        services: {
          weeks: {
            38: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 2,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            293: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 2,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 8,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            292: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 5,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            291: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 7,
              totalFoodOrders: 0,
            },
            290: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 2,
              avgPriceOfFood: 0,
              totalEarnings: 1,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            289: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              totalEarnings: 9,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            288: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 4,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 2,
              totalIssues: 12,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            287: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 2,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 5,
              avgPriceOfServices: 0,
            },
          },
          months: {
            9: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 0,
              avgPriceOfRooms: 0,
            },
          },
          name: "Services",
        },
      },
    },
  };

  let usr;
  const handleUser = async () => {
    const user = await add("vikumar.azad@gmail.com", analytics, "analytics");
    // const hashedPassword = await hash("123456789", 8);
    console.log(user);
  };

  return (
    <div>
      <h1>{JSON.stringify(usr)}</h1>
      <button onClick={() => handleUser()}>Click</button>
    </div>
  );
}
